### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by jdmcpeek** [jdmcpeek/weB-ohnanza#21]
@Steven-Wright spent literally two hours trying to figure out why the most basic angular directives wouldn't work, was looking into server issues, gzip, and finally I found that I wrote a typo into one of my src's....

`<!DOCTYPE html>
<html lang="en" ng-app="fuckEverything">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script src="./libs/angular-1.3.4.js"></script>
</head>
  <script>
    var fuckEverything = angular.module('fuckEverything', []);
    fuckEverything.controller('damnItAll', function($scope) {
      $scope.fuckyou = "FUCK YOU";
      $scope.god = ['loves Jesus', 'loves donuts', 'loves Jesus and Donuts'];
    });
  </script>
<body ng-controller="damnItAll">
  <ul>
    <li ng-repeat="g in god">
      God: {{g}}
    </li>
  </ul>
  You're both right!
</body>
</html>
`

**Comment by Steven-Wright** [comment]
wut
